# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66d9b79f6f95d78ad26ee5d5f1b698e5613dbbdc07842972c3373ef34b562a276db634aacc25f7bda85a38495baf0f3b8477a36971658d490014aca34a5dfef4

test:
  secret_key_base: 6ae0c47ed313e3b935a34907ea9ce2887d8ddd363e8dbbf237e5953b37263bec818ef3dd3136b77c9a83da158c692dc6bc3aabacaf9bf08b73c359d7add7a4e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
